In [2]:
import numpy as np

In [16]:
feature_map = np.arange(6).reshape(3,2).astype(np.float32)
print(feature_map)

[[0. 1.]
 [2. 3.]
 [4. 5.]]


In [17]:
weight = np.arange(6).reshape(2,3).astype(np.float32)
print(weight)

[[0. 1. 2.]
 [3. 4. 5.]]


In [9]:
m = 3
k = 2
n = 3

tile_m = 3
m_stride = m // tile_m

In [18]:
matmul_np_golden = np.matmul(feature_map, weight)
print(matmul_np_golden)

[[ 3.  4.  5.]
 [ 9. 14. 19.]
 [15. 24. 33.]]


In [ ]:
# tile_m: m维度拆分，feature map 拆分 batch
# 拆分 input， 每一份 拆分后的 input 和 weight 做matmul，之后所有结果做concat，
# 假设m拆了 tile_m 次，最后有 tile_m 个tensor做 在 m维度 concat
#  一般m叫batch方向，k是ic方向，n是oc方向
# 【m,k】* 【k,n】= 【m,n】
# 【n,ic】* 【ic, oc】 = 【n, oc】

In [22]:
matmul_tile_m_concat = None
for tile_m_id in range(tile_m):
    feature_map_tile_m= feature_map[tile_m_id*m_stride:(tile_m_id+1)*m_stride, :]
    matmul_tile_m = np.matmul(feature_map_tile_m, weight)
    if tile_m_id == 0:
        matmul_tile_m_concat = matmul_tile_m
        continue
    matmul_tile_m_concat = np.concatenate((matmul_tile_m_concat, matmul_tile_m), axis=0)
print((matmul_tile_m_concat == matmul_np_golden).all())

True
