In [1]:
import numpy as np

In [3]:
a = np.arange(6).reshape(3,2).astype(np.float32)
print(a)

[[0. 1.]
 [2. 3.]
 [4. 5.]]


In [4]:
b = np.arange(6).reshape(2,3).astype(np.float32)
print(b)

[[0. 1. 2.]
 [3. 4. 5.]]


In [6]:
matmul_np_golden = np.matmul(a,b)
print(matmul_np_golden)

[[ 3.  4.  5.]
 [ 9. 14. 19.]
 [15. 24. 33.]]


In [7]:
# tile_n: n维度拆分，只拆分weight，拆分后每一片weight和input做matmul，之后所有结果在n维度concat
#  一般m叫batch方向，k是ic方向，n是oc方向
# 【m,k】* 【k,n】= 【m,n】
# 【n,ic】* 【ic, oc】 = 【n, oc】

In [8]:
matmul_tile_n0 = np.matmul(a,b[:,:1])
print(matmul_tile_n0)

[[ 3.]
 [ 9.]
 [15.]]


In [9]:
matmul_tile_n1 = np.matmul(a,b[:,1:2])
print(matmul_tile_n1)

[[ 4.]
 [14.]
 [24.]]


In [10]:
matmul_tile_n2 = np.matmul(a,b[:,2:3])
print(matmul_tile_n2)

[[ 5.]
 [19.]
 [33.]]


In [11]:
matmul_tile_n_res = np.concatenate((matmul_tile_n0, matmul_tile_n1, matmul_tile_n2), axis=-1)
print(matmul_tile_n_res)

[[ 3.  4.  5.]
 [ 9. 14. 19.]
 [15. 24. 33.]]


In [12]:
print("n方向拆分前后比较: ", matmul_np_golden == matmul_tile_n_res)

n方向拆分前后比较:  [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [13]:
print("n方向拆分前后比较: ", (matmul_np_golden == matmul_tile_n_res).all())

n方向拆分前后比较:  True
